<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 4.7.3
 */

/**
 * Database `austin60_Database1`
 */

/* `austin60_Database1`.`Enemies` */
$Enemies = array(
  array('Name' => 'Aldia Warlock','AttackStyle' => 'Spells','Weakness' => 'Physical Attacks'),
  array('Name' => 'Alonne Knight','AttackStyle' => 'Physical Attacks','Weakness' => 'None'),
  array('Name' => 'Aldia Warlock','AttackStyle' => 'Dark','Weakness' => 'Physical'),
  array('Name' => 'Alonne Knight','AttackStyle' => 'Physical','Weakness' => 'None'),
  array('Name' => 'Alonne Knight Captain','AttackStyle' => 'Physical','Weakness' => 'Physical'),
  array('Name' => 'Amana Aberration','AttackStyle' => 'Physical','Weakness' => 'Physical'),
  array('Name' => 'Amana Priestess','AttackStyle' => 'Magic','Weakness' => 'None'),
  array('Name' => 'Archdrake Pilgrim','AttackStyle' => 'Physical','Weakness' => 'Physical'),
  array('Name' => 'Armored Skeleton','AttackStyle' => 'Physical','Weakness' => 'Physical'),
  array('Name' => 'Basilisk','AttackStyle' => 'Petrify','Weakness' => 'Magic'),
  array('Name' => 'Mounted Overseer','AttackStyle' => 'Dark','Weakness' => 'Magic'),
  array('Name' => 'Bell Keeper','AttackStyle' => 'All','Weakness' => 'None'),
  array('Name' => 'Bell Keeper Mage','AttackStyle' => 'Magic','Weakness' => 'None'),
  array('Name' => 'Bonewheel Skeleton','AttackStyle' => 'Physical','Weakness' => 'Fire'),
  array('Name' => 'Cragslipper','AttackStyle' => 'Physical','Weakness' => 'Physical'),
  array('Name' => 'Crystal Lizard','AttackStyle' => 'None','Weakness' => 'None'),
  array('Name' => 'Curse Jar','AttackStyle' => 'Curse','Weakness' => 'Breaking'),
  array('Name' => 'Darkdweller','AttackStyle' => 'Physical','Weakness' => 'Fire'),
  array('Name' => 'Darksucker','AttackStyle' => 'Physical','Weakness' => 'Fire'),
  array('Name' => 'Dark Priestess','AttackStyle' => 'Faith','Weakness' => 'None'),
  array('Name' => 'Desert Sorceress','AttackStyle' => 'Fire','Weakness' => 'Physical'),
  array('Name' => 'Dragon','AttackStyle' => 'Fire and Physical','Weakness' => 'Lightning'),
  array('Name' => 'Dragonfang Acolyte','AttackStyle' => 'Enchanted Physical','Weakness' => 'None'),
  array('Name' => 'Dragonfang Knight','AttackStyle' => 'Physical','Weakness' => 'None'),
  array('Name' => 'Drakekeeper','AttackStyle' => 'Physical','Weakness' => 'Physical'),
  array('Name' => 'Ducal Spider','AttackStyle' => 'Physical','Weakness' => 'Fire'),
  array('Name' => 'Executioner','AttackStyle' => 'Physical','Weakness' => 'Magic'),
  array('Name' => 'Flame Salamander','AttackStyle' => 'Fire','Weakness' => 'None'),
  array('Name' => 'Forrest Grotesque','AttackStyle' => 'Poison','Weakness' => 'None'),
  array('Name' => 'Foreign Wanderer','AttackStyle' => 'Physical','Weakness' => 'None'),
  array('Name' => 'Gaoler','AttackStyle' => 'Fire','Weakness' => 'Magic'),
  array('Name' => 'Great Basilisk','AttackStyle' => 'Petrify','Weakness' => 'Magic'),
  array('Name' => 'Great Poison Brumer','AttackStyle' => 'Corrosive','Weakness' => 'Physical'),
  array('Name' => 'Giant Warrior','AttackStyle' => 'Physical','Weakness' => 'None'),
  array('Name' => 'Greatsword Bell Keeper','AttackStyle' => 'Physical','Weakness' => 'None'),
  array('Name' => 'Great Giant Warrior','AttackStyle' => 'Physical','Weakness' => 'None'),
  array('Name' => 'Gyrm Warrior','AttackStyle' => 'Physical','Weakness' => 'None'),
  array('Name' => 'Gyrm Worker','AttackStyle' => 'Physical','Weakness' => 'Magic'),
  array('Name' => 'Hammersmith','AttackStyle' => 'Physical','Weakness' => 'Magic'),
  array('Name' => 'Heide Knight','AttackStyle' => 'Physical','Weakness' => 'None'),
  array('Name' => 'Hollow Crawler','AttackStyle' => 'Physical','Weakness' => 'None'),
  array('Name' => 'Hollow Infantry','AttackStyle' => 'Physical','Weakness' => 'Magic'),
  array('Name' => 'Hollow Mage','AttackStyle' => 'Dark','Weakness' => 'Physical'),
  array('Name' => 'Hollow Rogue','AttackStyle' => 'Physical','Weakness' => 'Magic'),
  array('Name' => 'Hollow Royal Soldier','AttackStyle' => 'Physical','Weakness' => 'Magic'),
  array('Name' => 'Hollow Peasant','AttackStyle' => 'Physical','Weakness' => 'Magic'),
  array('Name' => 'Hollow Priest','AttackStyle' => 'Magic','Weakness' => 'None'),
  array('Name' => 'Hollow Primal Knight','AttackStyle' => 'Physical','Weakness' => 'None'),
  array('Name' => 'Hollow Pyromancer','AttackStyle' => 'Fire','Weakness' => 'None'),
  array('Name' => 'Hollow Varangian','AttackStyle' => 'Physical','Weakness' => 'Physical'),
  array('Name' => 'Hunting Dog','AttackStyle' => 'Physical','Weakness' => 'None'),
  array('Name' => 'Hunting Rat','AttackStyle' => 'Physical','Weakness' => 'Fire'),
  array('Name' => 'Infantry','AttackStyle' => 'Physical','Weakness' => 'Magic'),
  array('Name' => 'Invisible Hollow','AttackStyle' => 'Physical','Weakness' => 'None'),
  array('Name' => 'Ironclad Soldier','AttackStyle' => 'Physical','Weakness' => 'Lightning'),
  array('Name' => 'Iron Warrior','AttackStyle' => 'Fire','Weakness' => 'None'),
  array('Name' => 'Leydia Pyromancer','AttackStyle' => 'Fire','Weakness' => 'Lightning'),
  array('Name' => 'Leydia Witch','AttackStyle' => 'Dark','Weakness' => 'None'),
  array('Name' => 'Lion Clan Warrior','AttackStyle' => 'Physical','Weakness' => 'None'),
  array('Name' => 'Masked Manikin','AttackStyle' => 'Physical','Weakness' => 'Magic'),
  array('Name' => 'Mongrel Ray','AttackStyle' => 'Physical','Weakness' => 'Fire'),
  array('Name' => 'Nimble Shadow','AttackStyle' => 'Physical','Weakness' => 'Magic'),
  array('Name' => 'Ogre','AttackStyle' => 'Physical','Weakness' => 'Fire'),
  array('Name' => 'Old Ironclad Soldier','AttackStyle' => 'Physical','Weakness' => 'Lightning'),
  array('Name' => 'Old Knight','AttackStyle' => 'Physical','Weakness' => 'Dark'),
  array('Name' => 'Parasitized Undead','AttackStyle' => 'Physical','Weakness' => 'Fire'),
  array('Name' => 'Petrifying Statue Cluster','AttackStyle' => 'Petrify','Weakness' => 'Breaking'),
  array('Name' => 'Poison Brumer','AttackStyle' => 'Corrosive','Weakness' => 'Fire'),
  array('Name' => 'Poison Moth','AttackStyle' => 'Poison','Weakness' => 'Fire'),
  array('Name' => 'Primal Knight','AttackStyle' => 'Physical','Weakness' => 'Magic'),
  array('Name' => 'Prowler Hound','AttackStyle' => 'Physical','Weakness' => 'Magic'),
  array('Name' => 'Prowling Magus','AttackStyle' => 'Magic','Weakness' => 'Lightning'),
  array('Name' => 'Red Crystal Lizard','AttackStyle' => 'Explosion','Weakness' => 'Ranged'),
  array('Name' => 'Roaming Soul','AttackStyle' => 'Physical','Weakness' => 'None'),
  array('Name' => 'Rotten Vermin','AttackStyle' => 'Poison','Weakness' => 'Lightning'),
  array('Name' => 'Royal Soldier','AttackStyle' => 'Physical','Weakness' => 'Magic'),
  array('Name' => 'Royal Swordsman','AttackStyle' => 'Physical','Weakness' => 'Magic'),
  array('Name' => 'Rupturing Hollow','AttackStyle' => 'Corrosive','Weakness' => 'Magic'),
  array('Name' => 'Skeleton','AttackStyle' => 'Physical','Weakness' => 'Physical'),
  array('Name' => 'Stone Knight','AttackStyle' => 'Physical','Weakness' => 'Dark'),
  array('Name' => 'Stone Soldier','AttackStyle' => 'Physical','Weakness' => 'Dark'),
  array('Name' => 'Stray Hound','AttackStyle' => 'Physical','Weakness' => 'Fire'),
  array('Name' => 'Swollen Mongrel','AttackStyle' => 'Physical','Weakness' => 'Fire'),
  array('Name' => 'Syan Soldier','AttackStyle' => 'Physical','Weakness' => 'Physical'),
  array('Name' => 'Tseldoran Settler','AttackStyle' => 'Faith','Weakness' => 'Magic'),
  array('Name' => 'Undead Aberration','AttackStyle' => 'Physical','Weakness' => 'Magic'),
  array('Name' => 'Undead Crypt Knight','AttackStyle' => 'Physical','Weakness' => 'Lightning'),
  array('Name' => 'Undead Devourer','AttackStyle' => 'Physical','Weakness' => 'Fire'),
  array('Name' => 'Undead Huntsman','AttackStyle' => 'Physical','Weakness' => 'Magic'),
  array('Name' => 'Undead Laborer','AttackStyle' => 'Physical','Weakness' => 'Magic'),
  array('Name' => 'Wall Spectre','AttackStyle' => 'Physical','Weakness' => 'Lightning')
);
