<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 4.7.3
 */

/**
 * Database `austin60_Database1`
 */

/* `austin60_Database1`.`Shields` */
$Shields = array(
  array('ShieldName' => 'Buckler','ShieldType' => 'Small','Requirement' => 'Strength/Dexterity','RequirementLevels' => '7/13'),
  array('ShieldName' => 'Small Leather Shield','ShieldType' => 'Small','Requirement' => 'Strength','RequirementLevels' => '5'),
  array('ShieldName' => 'Target Shield','ShieldType' => 'Small','Requirement' => 'Strength/Dexterity','RequirementLevels' => '8/12'),
  array('ShieldName' => 'Crimson Parma','ShieldType' => 'Small','Requirement' => 'Strength','RequirementLevels' => '6'),
  array('ShieldName' => 'Iron Parma','ShieldType' => 'Small','Requirement' => 'Strength','RequirementLevels' => '10'),
  array('ShieldName' => 'Foot Soldier Shield','ShieldType' => 'Small','Requirement' => 'Strength','RequirementLevels' => '6'),
  array('ShieldName' => 'Manikin Shield','ShieldType' => 'Small','Requirement' => 'Strength/Dexterity','RequirementLevels' => '9/12'),
  array('ShieldName' => 'Golden Falcon Shield','ShieldType' => 'Small','Requirement' => 'Strength/Dexterity','RequirementLevels' => '7/10'),
  array('ShieldName' => 'Benhart\'s Parma','ShieldType' => 'Small','Requirement' => 'Strength','RequirementLevels' => '7'),
  array('ShieldName' => 'Llewellyn Shield','ShieldType' => 'Small','Requirement' => 'Strength/Dexterity','RequirementLevels' => '9/7'),
  array('ShieldName' => 'Cleric\'s Parma','ShieldType' => 'Small','Requirement' => 'Strength/Dexterity','RequirementLevels' => '7/7'),
  array('ShieldName' => 'Cleric\'s Small Shield','ShieldType' => 'Small','Requirement' => 'Strength/Dexterity','RequirementLevels' => '8/12'),
  array('ShieldName' => 'Magic Shield','ShieldType' => 'Small','Requirement' => 'Strength/Dexterity','RequirementLevels' => '8/14'),
  array('ShieldName' => 'Cursed Bone Shield','ShieldType' => 'Small','Requirement' => 'Strength/Dexterity','RequirementLevels' => '12/12'),
  array('ShieldName' => 'Varangian Shield','ShieldType' => 'Small','Requirement' => 'Strength/Dexterity','RequirementLevels' => '9/11'),
  array('ShieldName' => 'Watcher\'s Shield','ShieldType' => 'Small','Requirement' => 'Strength/Dexterity','RequirementLevels' => '8/11'),
  array('ShieldName' => 'Phoenix Parma','ShieldType' => 'Small','Requirement' => 'Strength/Dexterity','RequirementLevels' => '9/10'),
  array('ShieldName' => 'Sunlight Parma','ShieldType' => 'Small','Requirement' => 'Strength/Dexterity','RequirementLevels' => '7/11'),
  array('ShieldName' => 'Transgressor\'s Leather Shield','ShieldType' => 'Small','Requirement' => 'Strength','RequirementLevels' => '7'),
  array('ShieldName' => 'Large Leather Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '7'),
  array('ShieldName' => 'Blue Wooden Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '6'),
  array('ShieldName' => 'Silver Eagle Kite Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '10'),
  array('ShieldName' => 'Old Knight\'s Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '24'),
  array('ShieldName' => 'Lion Clan Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '8'),
  array('ShieldName' => 'Archdrake Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '14'),
  array('ShieldName' => 'Mirrah Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '12'),
  array('ShieldName' => 'Drangleic Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '16'),
  array('ShieldName' => 'King\'s Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '16'),
  array('ShieldName' => 'Spirit Tree','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '10'),
  array('ShieldName' => 'Golden Wing Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '12'),
  array('ShieldName' => 'Moon Butterfly Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '6'),
  array('ShieldName' => 'Shield of the Insolent','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '10'),
  array('ShieldName' => 'Silverblack Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '16'),
  array('ShieldName' => 'Stone Parma','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '18'),
  array('ShieldName' => 'Grand Spirit Tree Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '10'),
  array('ShieldName' => 'Slumbering Dragon Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '14'),
  array('ShieldName' => 'Chaos Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '10'),
  array('ShieldName' => 'Wooden Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '7'),
  array('ShieldName' => 'Hollow Soldier Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '8'),
  array('ShieldName' => 'Royal Kite Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '12'),
  array('ShieldName' => 'Bone Shield','ShieldType' => 'Standard','Requirement' => 'Strength/Dexterity','RequirementLevels' => '8/8'),
  array('ShieldName' => 'Drakekeeper\'s Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '17'),
  array('ShieldName' => 'Porcine Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '9'),
  array('ShieldName' => 'Bell Keeper Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '7'),
  array('ShieldName' => 'Red Rust Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '17'),
  array('ShieldName' => 'Defender\'s Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '15'),
  array('ShieldName' => 'Black Dragon Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '15'),
  array('ShieldName' => 'Watchdragon Parma','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '10'),
  array('ShieldName' => 'Blossom Kite Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '12'),
  array('ShieldName' => 'Black Flamestone Parma','ShieldType' => 'Standard','Requirement' => 'Strength/Dexterity','RequirementLevels' => '8/10'),
  array('ShieldName' => 'Yellow Quartz Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '12'),
  array('ShieldName' => 'Bound Wooden Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '11'),
  array('ShieldName' => 'Homunculus Wooden Shield','ShieldType' => 'Standard','Requirement' => 'Strength','RequirementLevels' => '8'),
  array('ShieldName' => 'Loyce Shield','ShieldType' => 'Standard','Requirement' => 'Strength/Dexterity','RequirementLevels' => '12/15'),
  array('ShieldName' => 'Twin Dragon Greatshield','ShieldType' => 'Greatshield','Requirement' => 'Strength','RequirementLevels' => '20'),
  array('ShieldName' => 'Tower Shield','ShieldType' => 'Greatshield','Requirement' => 'Strength','RequirementLevels' => '30'),
  array('ShieldName' => 'Gyrm Greatshield','ShieldType' => 'Greatshield','Requirement' => 'Strength','RequirementLevels' => '32'),
  array('ShieldName' => 'Old Knight Greatshield','ShieldType' => 'Greatshield','Requirement' => 'Strength','RequirementLevels' => '28'),
  array('ShieldName' => 'Greatshield of Glory','ShieldType' => 'Greatshield','Requirement' => 'Strength','RequirementLevels' => '35'),
  array('ShieldName' => 'Drakekeeper\'s Greatshield','ShieldType' => 'Greatshield','Requirement' => 'Strength','RequirementLevels' => '37'),
  array('ShieldName' => 'Pate\'s Shield','ShieldType' => 'Greatshield','Requirement' => 'Strength','RequirementLevels' => '25'),
  array('ShieldName' => 'Mastodon Greatshield','ShieldType' => 'Greatshield','Requirement' => 'Strength','RequirementLevels' => '30'),
  array('ShieldName' => 'Havel\'s Greatshield','ShieldType' => 'Greatshield','Requirement' => 'Strength','RequirementLevels' => '45'),
  array('ShieldName' => 'Pursuer\'s Greatshield','ShieldType' => 'Greatshield','Requirement' => 'Strength','RequirementLevels' => '38'),
  array('ShieldName' => 'Reeve\'s Greatshield','ShieldType' => 'Greatshield','Requirement' => 'Strength','RequirementLevels' => '33'),
  array('ShieldName' => 'Orma\'s Greatshield','ShieldType' => 'Greatshield','Requirement' => 'Strength','RequirementLevels' => '33'),
  array('ShieldName' => 'Dragonrider Greatshield','ShieldType' => 'Greatshield','Requirement' => 'Strength','RequirementLevels' => '35'),
  array('ShieldName' => 'King\'s Mirror','ShieldType' => 'Greatshield','Requirement' => 'Strength','RequirementLevels' => '35'),
  array('ShieldName' => 'Rebel\'s Greatshield','ShieldType' => 'Greatshield','Requirement' => 'Strength','RequirementLevels' => '29'),
  array('ShieldName' => 'Wicked Eye Greatshield','ShieldType' => 'Greatshield','Requirement' => 'Strength','RequirementLevels' => '31')
);
