<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 4.7.3
 */

/**
 * Database `austin60_Database1`
 */

/* `austin60_Database1`.`Spells` */
$Spells = array(
  array('Name' => 'Med Heal','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '18'),
  array('Name' => 'Great Heal Excerpt','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '14'),
  array('Name' => 'Great Heal','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '28'),
  array('Name' => 'Soothing Sunlight','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '52'),
  array('Name' => 'Replenishment','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '16'),
  array('Name' => 'Resplendent Life','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '25'),
  array('Name' => 'Bountiful Sunlight','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '38'),
  array('Name' => 'Caressing Prayer','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '15'),
  array('Name' => 'Force','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '12'),
  array('Name' => 'Heal','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '12'),
  array('Name' => 'Wrath of the Gods','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '30'),
  array('Name' => 'Emit Force','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '20'),
  array('Name' => 'Heavenly Thunder','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '17'),
  array('Name' => 'Lightning Spear','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '22'),
  array('Name' => 'Great Lightning Spear','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '42'),
  array('Name' => 'Sunlight Spear','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '55'),
  array('Name' => 'Soul Appease','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '19'),
  array('Name' => 'Blinding Bolt','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '65'),
  array('Name' => 'Magic Barrier','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '14'),
  array('Name' => 'Great Magic Barrier','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '28'),
  array('Name' => 'Homeward','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '18'),
  array('Name' => 'Guidance','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '12'),
  array('Name' => 'Sacred Oath','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '25'),
  array('Name' => 'Unveil','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '13'),
  array('Name' => 'Perserverance','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '15'),
  array('Name' => 'Sunlight Blade','Type' => 'Miracle','Requirements' => 'Faith','RequirementLevels' => '36'),
  array('Name' => 'Fireball','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Fire Orb','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Great Fireball','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Great Chaos Fireball','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Firestorm','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Fire Tempest','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Chaos Storm','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Combustion','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Great Combustion','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Fire Whip','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Poison Mist','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Toxic Mist','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Acid Surge','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Lingering Flame','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Flame Swathe','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Forbidden Sun','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Flame Weapon','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Flash Sweat','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Iron Flesh','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Warmth','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Immolation','Type' => 'Pyromancy','Requirements' => 'None','RequirementLevels' => '0'),
  array('Name' => 'Soul Arrow','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '10'),
  array('Name' => 'Great Soul Arrow','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '14'),
  array('Name' => 'Heavy Soul Arrow','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '12'),
  array('Name' => 'Great Heavy Soul Arrow','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '16'),
  array('Name' => 'Homing Soul Arrow','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '25'),
  array('Name' => 'Heavy Homing Soul Arrow','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '35'),
  array('Name' => 'Homing Soul Mass','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '24'),
  array('Name' => 'Homing Crystal Soul Mass','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '32'),
  array('Name' => 'Soul Spear','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '40'),
  array('Name' => 'Crystal Soul Spear','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '53'),
  array('Name' => 'Shockwave','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '13'),
  array('Name' => 'Soul Spear Barrage','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '17'),
  array('Name' => 'Soul Shower','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '22'),
  array('Name' => 'Soul Greatsword','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '27'),
  array('Name' => 'Soul Vortex','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '37'),
  array('Name' => 'Soul Bolt','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '45'),
  array('Name' => 'Soul Geyser','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '64'),
  array('Name' => 'Magic Weapon','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '10'),
  array('Name' => 'Great Magic Weapon','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '18'),
  array('Name' => 'Crystal Magic Weapon','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '28'),
  array('Name' => 'Strong Magic Shield','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '19'),
  array('Name' => 'Yearn','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '19'),
  array('Name' => 'Hush','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '15'),
  array('Name' => 'Fall Control','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '15'),
  array('Name' => 'Hidden Weapon','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '14'),
  array('Name' => 'Repair','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '15'),
  array('Name' => 'Cast Light','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '14'),
  array('Name' => 'Chameleon','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '14'),
  array('Name' => 'Unleash Magic','Type' => 'Sorcery','Requirements' => 'Intelligence','RequirementLevels' => '58'),
  array('Name' => 'Dark Orb','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '12/20'),
  array('Name' => 'Dark Hail','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '19/12'),
  array('Name' => 'Dark Fog','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '25/14'),
  array('Name' => 'Affinity','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '40/24'),
  array('Name' => 'Dead Again','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '22/20'),
  array('Name' => 'Dark Weapon','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '16/14'),
  array('Name' => 'Whisper of Despair','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '24/18'),
  array('Name' => 'Repel','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '35/27'),
  array('Name' => 'Twisted Barricade','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '38/25'),
  array('Name' => 'Numbness','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '42/30'),
  array('Name' => 'Scraps of Life','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '8/12'),
  array('Name' => 'Darkstorm','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '12/21'),
  array('Name' => 'Resonant Soul','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '10/18'),
  array('Name' => 'Great Resonant Soul','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '13/26'),
  array('Name' => 'Climax','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '30/47'),
  array('Name' => 'Resonant Flesh','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '11/19'),
  array('Name' => 'Resonant Weapon','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '15/24'),
  array('Name' => 'Lifedrain Patch','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '20/35'),
  array('Name' => 'Profound Still','Type' => 'Hex','Requirements' => 'Intelligence/Faith','RequirementLevels' => '20/42'),
  array('Name' => '','Type' => '','Requirements' => '','RequirementLevels' => '')
);
